INSERT INTO INSTALLMENT_TYPE (ID, INSTALLMENT_NR)
    VALUES (1, 6);

INSERT INTO INSTALLMENT_TYPE (ID, INSTALLMENT_NR)
    VALUES (2, 9);

INSERT INTO INSTALLMENT_TYPE (ID, INSTALLMENT_NR)
    VALUES (3, 12);

INSERT INTO INSTALLMENT_TYPE (ID, INSTALLMENT_NR)
    VALUES (4, 24);

INSERT INTO INTEREST_RATE (ID, ADDED_ON, INTEREST_RATE)
    VALUES (1, CURDATE(), 0.3);
